packages/studio-base/src/components/AppBar/UploadFile/index.tsx
packages/studio-base/src/components/AppBar/index.tsx

fix : the unecpected closing of the tooltip when trying to copy the remote link after uploaded a file in studio 

fix: copy remote address

---

packages/studio-base/src/components/CoSceneEventView.tsx

feat: update moment view

---

eslint.config.cjs
packages/studio-base/src/components/DataSourceDialog/Connection.tsx
packages/studio-base/src/components/DataSourceDialog/DataSourceDialog.tsx
packages/studio-base/src/components/DataSourceDialog/View.tsx
packages/studio-base/src/dataSources/FoxgloveWebSocketDataSourceFactory.ts
packages/studio-base/src/dataSources/RemoteDataSourceFactory.tsx
packages/studio-base/src/dataSources/Ros1SocketDataSourceFactory.ts
packages/studio-base/src/dataSources/RosbridgeDataSourceFactory.ts
packages/studio-base/src/dataSources/VelodyneDataSourceFactory.ts
packages/studio-base/src/i18n/en/openDialog.ts
packages/studio-base/src/i18n/zh/openDialog.ts
packages/studio-base/src/providers/CoSceneCurrentLayoutProvider/IncompatibleLayoutVersionAlert.tsx
packages/studio-base/src/providers/CurrentLayoutProvider/IncompatibleLayoutVersionAlert.tsx
packages/studio-base/src/screens/LaunchingInDesktopScreen.tsx

feat: update open connect link dialog

---

packages/studio-base/src/components/Playlist.tsx
packages/studio-base/src/util/appConfig.ts
packages/studio-base/src/util/appURLState.ts
packages/studio-web/src/WebRoot.tsx
packages/studio-web/src/webpackConfigs.ts

feat:update hbs to hbsp

---

packages/studio-base/src/components/AppBar/AppStateBar.tsx

feat: update app state tips

---

packages/studio-base/src/components/AppBar/AppStateBar.tsx
packages/studio-base/src/components/CoScenePlaylistSyncAdapter.tsx
packages/studio-base/src/i18n/en/appBar.ts
packages/studio-base/src/i18n/zh/appBar.ts
packages/studio-web/src/webpackConfigs.ts

fix: file media

---

.github/workflows/release.yml
packages/studio-base/src/i18n/en/openDialog.ts
packages/studio-base/src/i18n/ja/general.ts
packages/studio-base/src/i18n/ja/openDialog.ts
packages/studio-base/src/i18n/zh/appSettings.ts
packages/studio-base/src/i18n/zh/incompatibleLayoutVersion.ts

chore: update coscene text

---

packages/studio-base/src/components/PlayerManager.tsx

fix: component multiple rerender

---

packages/studio-base/src/util/strPack.ts

fix: supor chart

---

packages/studio-web/src/CoSceneInit.tsx

fix: memo favicon

---

packages/studio-base/src/i18n/en/threeDee.ts
packages/studio-base/src/i18n/zh/threeDee.ts
packages/studio-base/src/panels/ThreeDeeRender/renderables/Grids.ts
packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts

feat: modify map height

---

packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

fix: visibilitychange removeEventListener

---

packages/studio-base/src/hooks/useCoSceneInitialDeepLinkState.ts

feat: make shure have a snapshort frame

---

packages/studio-base/src/hooks/useCoSceneInitialDeepLinkState.ts

fix: make shure have a snapshort frame

---

packages/studio-base/src/components/CoSceneChooser/index.tsx

fix: select file pagination component

---

packages/studio-base/src/AppSetting.ts
packages/studio-base/src/StudioApp.tsx
packages/studio-base/src/components/AppSettingsDialog/settings.tsx
packages/studio-base/src/components/CoSceneCreateEventContainer.tsx
packages/studio-base/src/components/CoSceneEventsSyncAdapter.tsx
packages/studio-base/src/components/CoScenePlaylistSyncAdapter.tsx
packages/studio-base/src/components/PlaybackControls/CoScenePlabackTimeMode.tsx
packages/studio-base/src/dataSources/CoSceneDataPlatformDataSourceFactory.ts
packages/studio-base/src/hooks/index.ts
packages/studio-base/src/hooks/useAppConfigurationValue.ts
packages/studio-base/src/panels/AnnotatedPlot/index.tsx
packages/studio-base/src/players/IterablePlayer/CoSceneIterablePlayer.ts
packages/studio-base/src/players/IterablePlayer/IIterableSource.ts
packages/studio-base/src/players/IterablePlayer/coScene-data-platform/DataPlatformIterableSource.ts
packages/studio-base/src/services/CoSceneConsoleApi.ts
packages/studio-desktop/src/renderer/Root.tsx
packages/studio-desktop/src/renderer/tsconfig.json
packages/studio-desktop/tsconfig.json
packages/studio-web/src/WebRoot.tsx
packages/studio-web/src/index.tsx
packages/studio-web/tsconfig.json

pref: app setting

---

packages/studio-base/src/Workspace.tsx
packages/studio-base/src/components/AppBar/AppStateBar.tsx
packages/studio-base/src/components/CoSceneCreateEventContainer.tsx

- **Update AppStateBar.tsx**
- **[COS-7396] fix: media state**
[COS-7396]: https://coscene.atlassian.net/browse/COS-7396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

COS-7396 fix: media state

---

packages/studio-base/src/hooks/useAppConfigurationValue.ts
packages/studio-base/src/util/appConfig.ts

fix: window is not defind

---

packages/studio-base/src/services/AmplitudeAnalytics.ts

fix: posthog register org_display_name

---

packages/studio-base/src/panels/ThreeDeeRender/renderables/Images/ImageRenderable.ts
packages/studio-base/src/panels/ThreeDeeRender/renderables/Images/WorkerImageDecoder.worker.ts

fix: H264 video b frame

---

packages/studio-base/src/components/BagView.tsx
packages/studio-base/src/components/Playlist.tsx
packages/studio-base/src/context/CoScenePlaylistContext.ts

fix: remove file

---

packages/studio-base/src/components/AppBar/index.tsx

fix: button color

---

packages/studio-base/src/components/PlayerManager.tsx
packages/studio-base/src/context/CoSceneBaseContext.ts

fix: page title

---

packages/studio-base/src/components/AppBar/CoSceneUserMenu.tsx
packages/studio-base/src/util/download.ts

feat: add studio version

---

packages/studio-base/src/components/BagView.tsx
packages/studio-base/src/components/Playlist.tsx

pref: open/remove file do not need reload

---

packages/studio-base/src/components/BagView.tsx

feat: donot show bag start time in generating media

---

packages/studio-base/src/players/IterablePlayer/coScene-data-platform/streamMessages.ts

feat: throw getStreams error

---

packages/studio-base/src/components/AppBar/AppStateBar.tsx
packages/studio-base/src/components/AppBar/index.tsx
packages/studio-base/src/components/PlayerManager.tsx
packages/studio-base/src/services/CoSceneConsoleApi.ts
packages/studio-web/src/CoSceneInit.tsx
packages/studio-web/src/WebRoot.tsx

- **pref: sync media**
- **Well, it's doing something.**

pref: notify hbs sync media

---

packages/studio-base/src/components/BagView.tsx

fix: bag file duration

---

packages/studio-desktop/src/renderer/Root.tsx

fix: open local file

---

packages/studio-base/src/components/BagView.tsx

- **fix: open local file**
- **pref: bag time display**
- **pref: bag time display**

pref: bag time display

---

packages/studio-base/src/Workspace.tsx

[COS-7509] pref: close datasource window

---

packages/studio-base/src/components/PlaybackControls/CoScenePlabackTimeMode.tsx
packages/studio-base/src/components/PlaybackControls/PlaybackQualityControls.tsx

pref: reload source

---

packages/studio-base/src/components/CoSceneCreateEventContainer.tsx

fix: Remove unused passingFile dependency in event creation

---

packages/studio-base/src/Workspace.tsx

pref: Debounce login toast for data source selection

---

packages/studio-base/src/Workspace.tsx

fix: login state toase

---

packages/studio-base/src/panels/ThreeDeeRender/renderables/FoxgloveGrid.ts
packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts

feat: foxglove grid support modify height

---

packages/studio-base/src/components/AppSettingsDialog/settings.tsx

fix: default lan

---

packages/studio-base/src/Workspace.tsx

[COS-7515](https://coscene.atlassian.net/browse/COS-7515)
[COS-7515]: https://coscene.atlassian.net/browse/COS-7515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support document listener

---

packages/studio-base/src/StudioApp.tsx
packages/studio-base/src/providers/CurrentLayoutProvider/index.tsx
packages/studio-base/src/providers/SharedProviders.tsx
packages/studio-base/src/services/CoSceneConsoleApi.ts
packages/studio-base/src/services/LayoutManager/CoSceneLayoutManager.ts

fix: improve layout initialization and handling in CoScene context

---

packages/studio-base/src/SharedRoot.tsx
packages/studio-web/src/index.tsx

feat: move sentry to shared root

---

packages/studio-base/package.json
packages/studio-base/src/components/CoSceneCreateEventContainer.tsx
packages/studio-base/src/i18n/cosEn/event.ts
packages/studio-base/src/i18n/cosZh/event.ts
yarn.lock

feat: teambition

---

packages/studio-base/src/components/AppSettingsDialog/settings.tsx
packages/studio-base/src/i18n/index.ts
packages/studio-base/src/services/CoSceneConsoleApi.ts

fix: default language

---

packages/studio-base/src/i18n/cosEn/websocket.ts
packages/studio-base/src/i18n/cosZh/websocket.ts
packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

fix: websocket inactice logic

---

packages/studio-base/package.json
packages/studio-base/src/components/AppBar/CoSceneLayoutButton/CoSceneLayoutRow.tsx
packages/studio-base/src/components/AppBar/CoSceneLayoutButton/LayoutSection.tsx
packages/studio-base/src/components/AppBar/CoSceneLayoutButton/index.tsx
packages/studio-base/src/components/CoSceneCurrentUserSyncAdapter.tsx
packages/studio-base/src/components/CoSceneEventView.tsx
packages/studio-base/src/components/PlaybackControls/Scrubber.tsx
packages/studio-base/src/components/PlaybackControls/index.tsx
packages/studio-base/src/context/AnalyticsProvider.tsx
packages/studio-base/src/context/CoSceneBaseContext.ts
packages/studio-base/src/context/CoSceneCurrentUserContext.ts
packages/studio-base/src/i18n/cosEn/layout.ts
packages/studio-base/src/i18n/cosZh/layout.ts
packages/studio-base/src/players/AnalyticsMetricsCollector.ts
packages/studio-base/src/providers/CoSceneUserProvider.tsx
packages/studio-base/src/services/AmplitudeAnalytics.ts
packages/studio-base/src/services/CoSceneConsoleApi.ts
yarn.lock

- Refactored the user role system, introducing enums and a weighting mechanism
- Optimized layout button and user permission logic
- Adjusted display rules for public and organization layouts
- Removed some unused analytics and metrics collection code
- Updated dependencies to their latest versions

feat: Updated user role weighting and layout permissions logic

---

packages/studio-base/src/components/AppBar/CoSceneLayoutButton/CoSceneLayoutRow.tsx
packages/studio-base/src/components/CoSceneEventView.tsx
packages/studio-base/src/components/PlaybackControls/Scrubber.tsx
packages/studio-base/src/components/PlaybackControls/index.tsx

feat: auth check

---

packages/studio-base/src/components/PlaybackControls/PlaybackQualityControls.tsx

feat: update doc link

---

packages/studio-base/src/components/MessagePathSyntax/MessagePathInput.tsx
packages/studio-base/src/panels/Table/index.tsx

fix: table panel message filter

---

packages/studio-base/src/components/AppBar/CoSceneUserMenu.tsx
packages/studio-base/src/components/AppBar/HelpMenu.tsx
packages/studio-base/src/components/AppBar/index.tsx
packages/studio-base/src/components/AppSettingsDialog/AppSettingsDialog.tsx
packages/studio-base/src/components/AppSettingsDialog/settings.tsx
packages/studio-base/src/components/DataSourceDialog/Start.tsx
packages/studio-base/src/components/EmptyPanelLayout.tsx
packages/studio-base/src/components/PanelLayout.tsx
packages/studio-base/src/components/PlaybackControls/PlaybackQualityControls.tsx
packages/studio-base/src/util/appConfig.ts
packages/studio-base/src/util/getDocsLink.ts

feat: update docs link

---

packages/studio-desktop/resources/icon/icon.icns
packages/studio-desktop/resources/icon/icon.png

feat: update coStudio icon

---

packages/studio-desktop/src/main/StudioWindow.ts

fix: update browser window theme

---

.github/workflows/release.yml

- **fix: costudio download url**
- **This is where it all begins...**
- **Transpiled mainframe.**
- **Is there an award for this?**
- **This is a basic implementation that works.**

fix: costudio download url

---

packages/studio-base/src/util/download.ts

feat: update costudio download url

---

.github/workflows/ci.yml
packages/studio-base/src/components/AppBar/CoSceneUserMenu.tsx

- **fix: get costudio version**
- **Herpy dooves.**

fix: get costudio version

---

packages/studio-base/src/providers/CoSceneLayoutManagerProvider.tsx
packages/studio-base/src/services/CoSceneConsoleApi.ts
packages/studio-base/src/services/CoSceneConsoleApiRemoteLayoutStorage.ts
packages/studio-base/src/services/CoSceneIRemoteLayoutStorage.ts
packages/studio-base/src/services/LayoutManager/CoSceneLayoutManager.ts

- **feat: coStudio support async remote layout to local**
- **lolwhat?**

feat: coStudio support sync remote layout to local

---

packages/studio-base/src/util/getDocsLink.ts

fix: update docs link

---

packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

hike: hidden error message

---

packages/studio-base/src/components/AppSettingsDialog/settings.tsx
packages/studio-base/src/components/DataSourceDialog/Start.tsx
packages/studio-base/src/dataSources/RemoteDataSourceFactory.tsx
packages/studio-base/src/i18n/index.ts

fix: doc link and language select

---

packages/studio-desktop/src/preload/index.ts

feat: update extension and layout storage site

---

packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

hake: disable auto disconnect realtime viz

---

packages/studio-base/src/dataSources/FoxgloveWebSocketDataSourceFactory.ts
packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

feat: support disable realtime viz auto disconnect

---

.gitignore
packages/studio-base/src/Workspace.tsx
packages/studio-base/src/components/ExtensionDetails.tsx
packages/studio-base/src/context/ExtensionCatalogContext.ts
packages/studio-base/src/context/ExtensionMarketplaceContext.ts
packages/studio-base/src/providers/ExtensionCatalogProvider.tsx
packages/studio-base/src/services/ExtensionLoader.ts
packages/studio-base/src/services/IdbExtensionLoader.ts
packages/studio-desktop/resources/icon/CoeIcon.png
packages/studio-desktop/src/common/types.ts
packages/studio-desktop/src/electronBuilderConfig.js
packages/studio-desktop/src/preload/extensions.ts
packages/studio-desktop/src/preload/index.ts
packages/studio-desktop/src/renderer/services/DesktopExtensionLoader.ts

- **feat: support coe suffix extension**
- **put code that worked where the code that didn't used to be**

feat: support coe suffix extension

---

packages/studio-base/src/services/CoSceneConsoleApi.ts

feat: update getStreams req header

---

packages/studio-base/src/Workspace.tsx
packages/studio-base/src/components/DocumentDropListener.tsx
packages/studio-base/src/i18n/cosEn/error.ts
packages/studio-base/src/i18n/cosZh/error.ts

feat: support web platform install plugin

---

packages/studio-base/src/StudioApp.tsx
packages/studio-base/src/Workspace.tsx
packages/studio-base/src/components/PlayerManager.tsx
packages/studio-base/src/context/Workspace/useOpenFile.tsx
packages/studio-base/src/hooks/useElectronFilesToOpen.ts

fix: dragged file  cannot upload to website

---

packages/studio-base/src/components/ExtensionsSettings/index.tsx

feat: disable marketplace enteries

---

packages/studio-base/src/components/AppSettingsDialog/AppSettingsDialog.tsx
packages/studio-desktop/src/main/rosPackageResources.ts

feat: restore ros package path

---

packages/studio-base/src/dataSources/FoxgloveWebSocketDataSourceFactory.ts
packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

feat: realtime viz add access token

---

packages/studio-base/src/dataSources/FoxgloveWebSocketDataSourceFactory.ts

[COS-7900] fix: device name display

---

packages/studio-base/src/i18n/en/dataCollection.ts
packages/studio-base/src/i18n/en/panels.ts
packages/studio-base/src/i18n/zh/dataCollection.ts
packages/studio-base/src/i18n/zh/panels.ts
packages/studio-base/src/panels/DataCollection/CallService.tsx
packages/studio-base/src/panels/DataCollection/DataCollection.tsx
packages/studio-base/src/panels/DataCollection/index.tsx
packages/studio-base/src/panels/DataCollection/thumbnail.png
packages/studio-base/src/panels/index.ts
packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

- **feat: update data collection panel style**
- **dope**

feat: update data collection panel style

---

packages/studio-base/src/panels/DataCollection/CallService.tsx
packages/studio-base/src/panels/DataCollection/DataCollection.tsx

feat: Added timing functionality to the data collection panel

---

packages/studio-base/src/panels/DataCollection/DataCollection.tsx

fix: default data collection task name

---

packages/studio-base/src/panels/DataCollection/DataCollection.tsx

fix: create data collection task

---

packages/studio-base/src/dataSources/FoxgloveWebSocketDataSourceFactory.ts

fix: ws login message

---

packages/studio-base/src/components/AppBar/UploadFile/ChoiceRecord.tsx
packages/studio-base/src/components/AppBar/UploadFile/UploadingFileList.tsx
packages/studio-base/src/components/AppBar/UploadFile/index.tsx
packages/studio-base/src/components/CoSceneChooser/index.tsx
packages/studio-base/src/context/UploadFilesContext.ts

fix: studio updat file target record link was wrong

---

packages/studio-base/src/i18n/en/appBar.ts

update: open in costudio prompt

---

packages/studio-base/src/components/AppBar/AppStateBar.tsx
packages/studio-base/src/components/AppBar/hooks/useAutoDisconnection.ts

fix: auto disconnection

---

packages/studio-base/src/components/CoSceneBaseSyncAdapter.tsx
packages/studio-base/src/components/CoSceneCreateEventContainer.tsx
packages/studio-base/src/components/RecordInfo/index.tsx
packages/studio-base/src/context/CoSceneBaseContext.ts
packages/studio-base/src/providers/CoSceneBaseProvider.tsx
packages/studio-base/src/services/CoSceneConsoleApi.ts

update get record schema function name
fix create moment custom field not display

fix: create moment

---

packages/studio-base/src/components/RecordInfo/index.tsx

feat: update record info

---

packages/studio-base/src/components/PlaybackControls/Scrubber.tsx

fix: create moment permission

---

packages/studio-base/src/components/CustomFieldProperty/editor/CustomFieldUserEditor.tsx
packages/studio-base/src/components/CustomFieldProperty/utils/convertCustomFieldValue.tsx

update: moment custom fields user field

---

packages/studio-base/src/components/CoSceneEventView.tsx
packages/studio-base/src/components/PlaybackControls/index.tsx

feat: edit moment check project is archived

---

packages/studio-base/src/panels/DataCollection/DataCollection.tsx
packages/studio-base/src/panels/DataCollection/types.ts

feat: data collection support skip capture

---

packages/studio-base/src/components/CoSceneEventsSyncAdapter.tsx
packages/studio-base/src/components/CoScenePlaylistSyncAdapter.tsx
packages/studio-base/src/components/PlayerManager.tsx
packages/studio-base/src/context/CoSceneConsoleApiContext.ts
packages/studio-base/src/context/PlayerSelectionContext.ts
packages/studio-base/src/i18n/cosEn/error.ts
packages/studio-base/src/i18n/cosZh/error.ts
packages/studio-base/src/index.ts
packages/studio-base/src/players/IterablePlayer/coScene-data-platform/DataPlatformIterableSource.ts
packages/studio-base/src/players/IterablePlayer/coScene-data-platform/streamMessages.ts
packages/studio-base/src/providers/SharedProviders.tsx
packages/studio-base/src/services/CoSceneConsoleApi.ts
packages/studio-base/src/services/CoSceneConsoleApiRemoteLayoutStorage.ts
packages/studio-base/src/services/api/CoSceneConsoleApi.ts
packages/studio-base/src/services/api/HttpError.ts
packages/studio-base/src/util/coscene/index.ts

- Changed import paths for ConsoleApi to use the new api directory.
- Added toast notification for unauthorized access in PlayerManager component.
- Updated error messages in English and Chinese for unauthorized access.

refactor: update ConsoleApi import paths and add error handling for unauthorized access

---

packages/studio-base/src/i18n/cosEn/error.ts
packages/studio-base/src/i18n/cosZh/error.ts
packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx

fix: update cancel action text in FoxgloveWebSocketPlayer to improve clarity

---

packages/studio-base/src/components/CoSceneCreateEventContainer.tsx
packages/studio-base/src/services/api/CoSceneConsoleApi.ts

fix: task permission

---

packages/studio-base/src/panels/DataCollection/DataCollection.tsx

feat: implement auto-scroll and user scroll detection in data collection log

---

.github/workflows/release.yml
packages/studio-base/src/util/appConfig.ts
packages/studio-base/src/util/download.ts

feat: update release wf

---

packages/studio-base/src/components/CoSceneCreateEventContainer.tsx

fix: prevent setting assignee to an array in UserSelect component

---

packages/studio-base/src/components/CoSceneCreateEventContainer.tsx
packages/studio-base/src/components/CustomFieldProperty/editor/CustomFieldEnumEditor.tsx
packages/studio-base/src/components/CustomFieldProperty/utils/convertCustomFieldValue.tsx
packages/studio-base/src/components/RecordInfo/RecordLabelSelector.tsx
packages/studio-base/src/components/UserSelect.tsx

feat: enhance user and custom field selection with Chip rendering and multiple value support

---

packages/studio-base/src/Workspace.tsx

fix: update hidden item logic in WorkspaceContent and filter out hidden items from the sidebar

---

packages/theme/src/components/MuiFormLabel.ts

feat: add asterisk styling to MuiFormLabel component

---

packages/studio-base/src/panels/DataCollection/DataCollection.tsx

fix: replace Date with dayjs for consistent timestamp formatting in DataCollection component

---

packages/studio-base/src/components/AppBar/DataSource.tsx

fix: conditionally render RealTimeVizLinkState based on linkType in DataSource component

---

packages/studio-base/src/components/CoSceneEventView.tsx

fix: name only mode of EventViewComponent in CoSceneEventView

---

packages/studio-base/src/Workspace.tsx
packages/studio-base/src/context/NativeAppMenuContext.ts
packages/studio-base/src/hooks/useNativeAppMenuEvent.ts
packages/studio-desktop/src/common/types.ts

feat: add support for new help menu options and implement native app menu event handling

---

packages/studio-base/src/components/UserSelect.tsx

fix: user avatar

---

packages/studio-base/src/i18n/cosEn/event.ts
packages/studio-base/src/i18n/cosZh/event.ts

fix: update syncTaskTooltip text to reflect correct navigation path in event translations for English and Chinese

---

packages/studio-base/src/components/UserSelect.tsx
packages/studio-base/src/util/download.ts

fix: update UserSelect component to handle avatar rendering more consistently and return default version on error in download utility

---

packages/mcap-support/src/parseChannel.ts
packages/studio-base/src/players/RosbridgePlayer.ts

detail in https://github.com/foxglove/rosmsg2-serialization/commit/00cfc6123c2416237305967c53b66a35284692a3

fix: @foxglove/rosmsg2-serialization breaking change

---

packages/studio-base/src/i18n/cosEn/layout.ts

fix: record capital

---

packages/studio-base/package.json
packages/studio-base/src/components/AppBar/CoSceneLayoutButton/CoSceneLayoutRow.tsx
packages/studio-base/src/components/CoSceneCurrentUserSyncAdapter.tsx
packages/studio-base/src/i18n/cosZh/layout.ts
packages/studio-base/src/services/api/CoSceneConsoleApi.ts
packages/studio-base/src/util/permission/endpoint/index.ts
yarn.lock

fix: update @coscene-io/cosceneapis-es to version 0.0.376 and refactor user role synchronization logic in CoSceneCurrentUserSyncAdapter component

---

packages/studio-base/src/components/CreateEventContainer/component/EventForm.tsx
packages/studio-base/src/components/CreateEventContainer/index.tsx

fix: remove conditional check for imageFile in CreateEventContainer and streamline updateMask paths in EventForm (#937)

---

packages/studio-base/src/components/CoSceneChooser/index.tsx
packages/studio-base/src/components/CoSceneChooser/types.ts
packages/studio-base/src/components/SettingsTreeEditor/inputs/CommonResourceSelecter.tsx
packages/studio-base/src/i18n/cosEn/playList.ts
packages/studio-base/src/i18n/cosEn/settings.ts
packages/studio-base/src/i18n/cosZh/playList.ts
packages/studio-base/src/i18n/cosZh/settings.ts

feat: update CoSceneChooser dialog titles and enhance localization for project resources selection

---

packages/studio-base/src/components/CoSceneChooser/index.tsx

fix: chooser dialog title

---

packages/studio-base/src/components/CreateEventContainer/index.tsx

fix: set maxWidth for Stack in CreateEventContainer to improve layout consistency

---

packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx

feat: add maxHeight and overflow properties to MenuProps in FieldInput for improved dropdown usability

---

packages/studio-base/src/components/CreateEventContainer/index.tsx
packages/studio-base/src/i18n/cosEn/event.ts
packages/studio-base/src/i18n/cosZh/event.ts

feat: add field configuration button and update translations for event management

---

packages/studio-base/src/components/CustomFieldProperty/utils/convertCustomFieldValue.tsx
packages/studio-base/src/i18n/en/general.ts
packages/studio-base/src/i18n/zh/general.ts

feat: update ConvertCustomFieldValue to handle multiple users and add unknown field translation

---

packages/studio-base/src/components/CreateEventContainer/index.tsx
packages/studio-base/src/i18n/cosEn/event.ts
packages/studio-base/src/i18n/cosZh/event.ts

fix: update button text and translations for save functionality in CreateEventContainer and event localization

---

packages/studio-base/src/components/CustomFieldProperty/editor/CustomFieldEnumEditor.tsx

refactor: extract value calculation for Autocomplete component in CustomFieldEnumEditor for improved readability

---

packages/studio-base/src/components/AppBar/UploadFile/ChoiceRecord.tsx
packages/studio-base/src/components/AppBar/UploadFile/index.tsx
packages/studio-base/src/components/CoSceneChooser/ChooserComponent.tsx
packages/studio-base/src/components/CoSceneChooser/CreateRecordForm.tsx
packages/studio-base/src/components/CoSceneChooser/index.tsx
packages/studio-base/src/components/CoSceneChooser/types.ts
packages/studio-base/src/components/Playlist.tsx
packages/studio-base/src/components/SettingsTreeEditor/inputs/CommonResourceSelecter.tsx

refactor: rename defaultRecordName to defaultRecordDisplayName and add defaultProject prop across multiple components for consistency

---

packages/studio-base/src/components/AppBar/CoSceneUserMenu.tsx
packages/studio-base/src/i18n/cosEn/appBar.ts
packages/studio-base/src/i18n/cosZh/appBar.ts
packages/studio-base/src/util/download.ts

[COS-8679] feat: user feedback

---

packages/studio-base/src/components/CustomFieldProperty/field/CustomFieldValueFieldDisplay.tsx

[COS-8621] Custom Field Value Field Display do not need requird

---

packages/studio-base/src/panels/Plot/OffscreenCanvasRenderer.ts
packages/studio-base/src/panels/Plot/Plot.tsx
packages/studio-base/src/panels/Plot/PlotCoordinator.ts

fix: chart destroyed

---

packages/studio-base/src/i18n/en/dataCollection.ts
packages/studio-base/src/i18n/zh/dataCollection.ts
packages/studio-base/src/panels/DataCollection/DataCollection.tsx

fix: collection task

---

packages/studio-base/src/components/AppSettingsDialog/AppSettingsDialog.tsx

fix: app setting dialog add padding

---

packages/studio-base/src/components/Tasks/TasksList/components/TaskView.tsx
packages/studio-base/src/i18n/en/task.ts
packages/studio-base/src/i18n/zh/task.ts

feat: focuse task add success toast

---

packages/studio-base/src/components/Tasks/TaskDetailDrawer/components/LinkedDevicesTable/components/DevicesTable.tsx
packages/studio-base/src/components/Tasks/TaskDetailDrawer/components/LinkedRecordsTable/components/RecordTable.tsx
packages/studio-base/src/components/Tasks/TaskDetailDrawer/components/LinkedRecordsTable/index.tsx
packages/studio-base/src/components/Tasks/TaskDetailDrawer/index.tsx

fix: task link table pagination

---

packages/studio-base/src/components/AppBar/AppMenu.tsx
packages/studio-base/src/i18n/en/appBar.ts
packages/studio-base/src/i18n/zh/appBar.ts

fix: rename open to open home page

---

packages/studio-base/src/components/Tasks/TaskDetailDrawer/index.tsx
packages/studio-base/src/components/Tasks/TasksList/components/TaskView.tsx
packages/studio-base/src/panels/DataCollection/DataCollection.tsx
packages/studio-base/src/panels/DataCollection/DataCollectionContext.tsx

fix: reset filters on task selection and optimize DataCollection component with memoization

---

packages/studio-base/src/components/DataSourceDialog/Start.tsx
packages/studio-base/src/components/Tasks/TaskPanel.tsx

fix: adjust TaskPanel dimensions and improve layout responsiveness in DataSourceDialog

---

packages/studio-base/src/components/PlayerManager.tsx
packages/studio-base/src/context/CoSceneBaseContext.ts

feat: add taskId to BaseInfo type and implement focused task handling in useBeforeConnectionSource

---

packages/studio-base/src/components/Tasks/TaskPanel.tsx
packages/studio-base/src/components/Tasks/TasksList/components/TaskView.tsx
packages/studio-base/src/panels/DataCollection/DataCollection.tsx
packages/studio-base/src/panels/DataCollection/index.tsx

- **update: pagesize**
- **feat: integrate toast notifications for task focus updates and add Toaster component in DataCollection panel**

feat: integrate toast notifications for task focus updates and add Toaster component in DataCollection panel

---

packages/studio-base/src/components/CoSceneBaseSyncAdapter.tsx

refactor: simplify custom field schema fetching logic in BaseSyncAdapter component

---

packages/studio-base/src/components/Events/CreateEventContainer/component/EventForm.tsx

feat: manage image URL lifecycle in EventForm component using data URL for CSP compliance

---

packages/studio-base/src/Workspace.tsx

fix: logout logic

---

packages/studio-desktop/src/webpackRendererConfig.ts
packages/studio-web/src/webpackConfigs.ts

fix: cos-config add build time

---

desktop/renderer/index.ts
packages/studio-base/src/AppSetting.ts
packages/studio-base/src/components/AppBar/AppStateBar.tsx
packages/studio-base/src/components/AppSettingsDialog/AppSettingsDialog.tsx
packages/studio-base/src/components/AppSettingsDialog/settings.tsx
packages/studio-base/src/components/PlayerManager.tsx
packages/studio-base/src/components/SubscriptionEntitlementSyncAdapter.tsx
packages/studio-base/src/hooks/index.ts
packages/studio-base/src/hooks/useAppConfigurationValue.ts
packages/studio-base/src/i18n/en/appSettings.ts
packages/studio-base/src/i18n/zh/appSettings.ts
packages/studio-base/src/panels/AnnotatedPlot/index.tsx
packages/studio-web/src/WebRoot.tsx

[COS-8973] feat: realtime viz add custom inactivity Timeout

---

packages/studio-base/src/components/AppBar/DataSource.tsx
packages/studio-base/src/i18n/en/appBar.ts
packages/studio-base/src/i18n/zh/appBar.ts
packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx
packages/studio-base/src/players/types.ts
packages/ws-protocol/src/FoxgloveClient.ts
packages/ws-protocol/src/types.ts

feat: support networkStatus

---

packages/studio-base/src/i18n/zh/threeDee.ts
packages/studio-base/src/panels/ThreeDeeRender/ModelCache.ts

fix: update meshUpAxis translation and change default meshUpAxis to z_up

---

packages/studio-base/src/panels/ThreeDeeRender/renderables/Images/WorkerImageDecoder.worker.ts

fix: streamline frame type handling in H264 decoder

---

packages/studio-base/src/i18n/en/appBar.ts
packages/studio-base/src/i18n/zh/appBar.ts

fix: update mediaGenerationError message for clarity in appBar translations

---

packages/studio-base/src/panels/ThreeDeeRender/renderables/Images/WorkerImageDecoder.worker.ts

feat: enhance H.264 frame parsing and type detection in WorkerImageDecoder (#1015)

---

packages/studio-base/src/panels/Plot/OffscreenCanvasRenderer.ts
packages/studio-base/src/panels/Plot/Plot.tsx
packages/studio-base/src/panels/Plot/PlotCoordinator.ts
packages/studio-base/src/panels/Plot/builders/CustomDatasetsBuilder.ts
packages/studio-base/src/panels/Plot/builders/IDatasetsBuilder.ts
packages/studio-base/src/panels/Plot/builders/TimestampDatasetsBuilder.ts

feat: implement explicit destroy method for datasets builders to enhance resource management

---

packages/studio-base/src/components/AppBar/DataSource.tsx

fix: add lodash check for non-empty network status in RealTimeVizLinkState component

---

packages/studio-base/src/components/AppBar/CoSceneUserMenu.tsx
packages/studio-base/src/components/PlayerManager.tsx
packages/studio-base/src/context/CoreDataContext.ts
packages/studio-base/src/context/PlayerSelectionContext.ts
packages/studio-base/src/providers/CoreDataProvider.tsx

fix: update selectSource function to handle undefined sourceId and improve CoreDataStore reset functionality

---

packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx
packages/studio-base/src/players/TopicAliasingPlayer/TopicAliasingPlayer.ts
packages/ws-protocol/src/parse.ts
packages/ws-protocol/src/types.ts

feat: add ETag handling for asset fetching in WebSocket players and update related parsing logic

---

packages/studio-base/src/components/AppBar/DataSource.tsx
packages/studio-base/src/players/IterablePlayer/coScene-data-platform/DataPlatformIterableSource.ts
packages/studio-base/src/players/IterablePlayer/coScene-data-platform/streamMessages.ts

feat: enhance DataPlatformIterableSource to handle message deserialization errors and differentiate between message events and problems

---

packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx
packages/studio-base/src/players/FoxgloveWebSocketPlayer/worker.ts
packages/ws-protocol/src/FoxgloveClient.ts
packages/ws-protocol/src/parse.ts
packages/ws-protocol/src/types.ts

feat: enhance WebSocket message handling by adding receiveTime to messages and updating syncTime logic

---

packages/studio-base/src/components/AppSettingsDialog/settings.tsx
packages/studio-base/src/i18n/en/appSettings.ts
packages/studio-base/src/i18n/zh/appSettings.ts

feat: add retention window notification and update settings dialog for effective changes

---

packages/studio-base/src/AppSetting.ts
packages/studio-base/src/components/PlaybackControls/index.tsx
packages/studio-base/src/components/PlaybackControls/sharedHelpers.ts
packages/studio-base/src/components/PlaybackSpeedControls.tsx
packages/studio-base/src/i18n/cosEn/general.ts
packages/studio-base/src/i18n/cosZh/general.ts
packages/studio-base/src/i18n/en/general.ts
packages/studio-base/src/i18n/en/index.ts
packages/studio-base/src/i18n/en/rawMessages.ts
packages/studio-base/src/i18n/en/table.ts
packages/studio-base/src/i18n/zh/general.ts
packages/studio-base/src/i18n/zh/index.ts
packages/studio-base/src/i18n/zh/rawMessages.ts
packages/studio-base/src/i18n/zh/table.ts
packages/studio-base/src/panels/RawMessages/Toolbar.tsx
packages/studio-base/src/panels/Table/index.tsx

feat: add internationalization support for RawMessages and Table panels with translation integration

---

packages/studio-base/src/components/PlaybackControls/SeekStepControls.tsx
packages/studio-base/src/components/PlaybackControls/index.tsx
packages/studio-base/src/components/PlaybackControls/sharedHelpers.ts
packages/studio-base/src/i18n/cosEn/general.ts
packages/studio-base/src/i18n/cosZh/general.ts
packages/studio-base/src/players/IterablePlayer/IterablePlayer.ts

feat: enhance PlaybackControls with SeekStepControls and update seek step validation

---

packages/studio-base/src/panels/Tab/index.tsx

fix: update EmptyPanelLayout tabId to use panelId directly for consistency

---

packages/studio-web/src/WebRoot.tsx

feat: add PersistentCacheDataSourceFactory to WebRoot data sources

---

packages/studio-base/src/i18n/en/appBar.ts
packages/studio-base/src/i18n/zh/appBar.ts

fix: update networkStatusHelp translation for clarity in appBar.ts

---

packages/studio-base/src/components/TimeBasedChart/TimeBasedChartTooltipContent.tsx

fix: update TimeBasedChartTooltipContent to display absolute time for the last item instead of the first

---

packages/studio-base/src/Workspace.tsx
packages/studio-base/src/components/AppSettingsDialog/AppSettingsDialog.tsx
packages/studio-base/src/dataSources/FoxgloveWebSocketDataSourceFactory.ts
packages/studio-desktop/src/renderer/Root.tsx
packages/studio-web/src/WebRoot.tsx

feat: disable Persistent Cache

---

packages/studio-base/src/components/CoSceneLayout/LayoutTableRow.tsx
packages/studio-base/src/components/CoSceneLayout/createLayout/ImportFromFileDialog.tsx
packages/studio-base/src/services/CoSceneConsoleApiRemoteLayoutStorage.ts
packages/studio-base/src/services/CoSceneIRemoteLayoutStorage.ts
packages/studio-base/src/util/coscene/index.ts

fix: import json with null value

---

packages/studio-base/src/util/coscene/index.ts

fix: replace undefined by null

---

packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx
packages/ws-protocol/src/types.ts

- **Revert "Feat：realtime support message time (#1003)"**
- **update**
- **update**

fix: realtime viz time

---

packages/studio-base/src/components/CoSceneLayout/CoSceneLayoutContent.tsx

fix: all layouts folder

---

packages/studio-base/src/components/CoSceneLayout/CoSceneLayoutContent.tsx
packages/studio-base/src/components/CoSceneLayout/CoSceneLayoutDrawer.tsx
packages/studio-base/src/components/CoSceneLayout/CopyLayoutDialog.tsx
packages/studio-base/src/components/CoSceneLayout/CurrentLayoutButton.tsx
packages/studio-base/src/components/CoSceneLayout/MoveToFolderDialog.tsx
packages/studio-base/src/components/CoSceneLayout/RenameLayoutDialog.tsx
packages/studio-base/src/components/CoSceneLayout/createLayout/CopyFromOtherProjectDialog.tsx
packages/studio-base/src/components/CoSceneLayout/createLayout/CreateBlankLayoutDialog.tsx
packages/studio-base/src/components/CoSceneLayout/createLayout/ImportFromFileDialog.tsx
packages/studio-base/src/components/CoSceneLayout/createLayout/ProjectLayoutSelector.tsx
packages/studio-base/src/components/CoSceneLayout/createLayout/SelectFolder.tsx
packages/studio-base/src/components/CoSceneLayoutBrowser/CoSceneUnsavedChangesPrompt.tsx

fix: layout name max length; drawer style

---

packages/studio-base/src/PanelAPI/useMessageReducer.ts

fix: useMessageReducer snapshort request

---

packages/studio-base/src/Workspace.tsx
packages/studio-base/src/components/AppBar/CoSceneUserMenu.tsx
packages/studio-base/src/components/AppBar/DataSource.tsx
packages/studio-base/src/components/CoSceneCurrentUserSyncAdapter.tsx
packages/studio-base/src/components/DataSourceDialog/Start.tsx
packages/studio-base/src/components/Events/CreateEventContainer/index.tsx
packages/studio-base/src/components/Tasks/TaskDetailDrawer/components/LinkedDevicesTable/components/DevicesTable.tsx
packages/studio-base/src/components/Tasks/TaskDetailDrawer/components/LinkedRecordsTable/components/RecordTable.tsx
packages/studio-base/src/components/Tasks/TaskDetailDrawer/useSelectSource.ts
packages/studio-base/src/dataSources/CoSceneDataPlatformDataSourceFactory.ts
packages/studio-base/src/dataSources/RemoteDataSourceFactory.tsx
packages/studio-base/src/panels/DataCollection/DataCollection.tsx
packages/studio-base/src/panels/DataCollection/utils.ts

refactor: replace APP_CONFIG with getDomainConfig for domain handling across multiple components

---

packages/studio-base/src/components/MessagePipeline/store.ts
packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.tsx
packages/ws-protocol/src/parse.ts
packages/ws-protocol/src/types.ts

fix: update etag handling in MessagePipeline and FoxgloveWebSocketPlayer, remove unused etag in parseServerMessage

---

packages/studio-base/src/panels/UserScriptEditor/Sidebar/ScriptsList.tsx

fix: user script build
